/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssessmentResult {
  'result' : AssessmentResultType,
  'assessmentType' : AssessmentType,
  'timestamp' : Time,
  'assessmentId' : string,
}
export type AssessmentResultType = { 'feedback' : string } |
  { 'score' : bigint } |
  { 'success' : boolean };
export type AssessmentType = { 'quiz' : null } |
  { 'codingChallenge' : null };
export interface Certificate {
  'id' : string,
  'userName' : string,
  'completionDate' : bigint,
  'userId' : Principal,
  'codingChallengeResults' : Array<CodingChallengeResult>,
  'quizResults' : Array<QuizResult>,
  'courseTitle' : string,
  'engagementScore' : bigint,
  'courseId' : CourseId,
}
export interface CodingChallenge {
  'id' : string,
  'title' : string,
  'description' : string,
}
export interface CodingChallengeAttempt {
  'avgScore' : bigint,
  'attempts' : bigint,
  'challengeId' : string,
}
export interface CodingChallengeResult {
  'title' : string,
  'testCasesPassed' : bigint,
  'score' : bigint,
  'challengeId' : string,
  'totalTestCases' : bigint,
}
export interface Course {
  'id' : CourseId,
  'title' : string,
  'codingChallenges' : Array<CodingChallenge>,
  'description' : string,
  'lessons' : Array<Lesson>,
  'price' : bigint,
  'quizzes' : Array<Quiz>,
}
export type CourseId = string;
export interface CourseProgress {
  'totalLessons' : bigint,
  'progress' : bigint,
  'completedLessons' : bigint,
  'courseId' : CourseId,
}
export interface EngagementMetrics {
  'videoEngagement' : Array<VideoEngagement>,
  'codingChallengeAttempts' : Array<CodingChallengeAttempt>,
  'attentionScore' : bigint,
  'quizTries' : Array<QuizTry>,
}
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'duration' : bigint,
  'isCompleted' : boolean,
  'description' : string,
  'videoBlob' : { 'id' : string, 'url' : string },
}
export type LessonId = string;
export interface Quiz {
  'id' : string,
  'title' : string,
  'questions' : Array<string>,
}
export interface QuizResult {
  'title' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
  'quizId' : string,
}
export interface QuizTry {
  'avgScore' : bigint,
  'attempts' : bigint,
  'quizId' : string,
}
export type Result = { 'ok' : Course } |
  { 'err' : string };
export type Result_1 = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_2 = { 'ok' : Array<Course> } |
  { 'err' : string };
export type Result_3 = { 'ok' : [] | [Course] } |
  { 'err' : string };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SystemHealth {
  'courseCount' : bigint,
  'initializationComplete' : boolean,
  'adminAssigned' : boolean,
  'coursesLoaded' : boolean,
  'systemReady' : boolean,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'id' : Principal,
  'isInstructor' : boolean,
  'earnedCertificates' : Array<Certificate>,
  'assessmentHistory' : Array<AssessmentResult>,
  'engagementMetrics' : EngagementMetrics,
  'name' : string,
  'purchasedCourses' : Array<CourseId>,
  'courseProgress' : Array<CourseProgress>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoEngagement {
  'participationScore' : bigint,
  'lessonId' : LessonId,
  'attentionScore' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'finalizeCoursePurchase' : ActorMethod<[string, string], Result_1>,
  'getCallerUserProfile' : ActorMethod<[], Result_1>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[string], Result_3>,
  'getCourses' : ActorMethod<[], Result_2>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSystemHealth' : ActorMethod<[], SystemHealth>,
  'getUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], Result_1>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCoursePrice' : ActorMethod<[string, bigint], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];