/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CodingChallengeResult = IDL.Record({
  'title' : IDL.Text,
  'testCasesPassed' : IDL.Nat,
  'score' : IDL.Nat,
  'challengeId' : IDL.Text,
  'totalTestCases' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'title' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'quizId' : IDL.Text,
});
export const CourseId = IDL.Text;
export const Certificate = IDL.Record({
  'id' : IDL.Text,
  'userName' : IDL.Text,
  'completionDate' : IDL.Int,
  'userId' : IDL.Principal,
  'codingChallengeResults' : IDL.Vec(CodingChallengeResult),
  'quizResults' : IDL.Vec(QuizResult),
  'courseTitle' : IDL.Text,
  'engagementScore' : IDL.Nat,
  'courseId' : CourseId,
});
export const AssessmentResultType = IDL.Variant({
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'success' : IDL.Bool,
});
export const AssessmentType = IDL.Variant({
  'quiz' : IDL.Null,
  'codingChallenge' : IDL.Null,
});
export const Time = IDL.Int;
export const AssessmentResult = IDL.Record({
  'result' : AssessmentResultType,
  'assessmentType' : AssessmentType,
  'timestamp' : Time,
  'assessmentId' : IDL.Text,
});
export const LessonId = IDL.Text;
export const VideoEngagement = IDL.Record({
  'participationScore' : IDL.Nat,
  'lessonId' : LessonId,
  'attentionScore' : IDL.Nat,
});
export const CodingChallengeAttempt = IDL.Record({
  'avgScore' : IDL.Nat,
  'attempts' : IDL.Nat,
  'challengeId' : IDL.Text,
});
export const QuizTry = IDL.Record({
  'avgScore' : IDL.Nat,
  'attempts' : IDL.Nat,
  'quizId' : IDL.Text,
});
export const EngagementMetrics = IDL.Record({
  'videoEngagement' : IDL.Vec(VideoEngagement),
  'codingChallengeAttempts' : IDL.Vec(CodingChallengeAttempt),
  'attentionScore' : IDL.Nat,
  'quizTries' : IDL.Vec(QuizTry),
});
export const CourseProgress = IDL.Record({
  'totalLessons' : IDL.Nat,
  'progress' : IDL.Nat,
  'completedLessons' : IDL.Nat,
  'courseId' : CourseId,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'isInstructor' : IDL.Bool,
  'earnedCertificates' : IDL.Vec(Certificate),
  'assessmentHistory' : IDL.Vec(AssessmentResult),
  'engagementMetrics' : EngagementMetrics,
  'name' : IDL.Text,
  'purchasedCourses' : IDL.Vec(CourseId),
  'courseProgress' : IDL.Vec(CourseProgress),
});
export const Result_1 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const CodingChallenge = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
  'videoBlob' : IDL.Record({ 'id' : IDL.Text, 'url' : IDL.Text }),
});
export const Quiz = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'questions' : IDL.Vec(IDL.Text),
});
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'codingChallenges' : IDL.Vec(CodingChallenge),
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
  'price' : IDL.Nat,
  'quizzes' : IDL.Vec(Quiz),
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Opt(Course),
  'err' : IDL.Text,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(Course),
  'err' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SystemHealth = IDL.Record({
  'courseCount' : IDL.Nat,
  'initializationComplete' : IDL.Bool,
  'adminAssigned' : IDL.Bool,
  'coursesLoaded' : IDL.Bool,
  'systemReady' : IDL.Bool,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const Result = IDL.Variant({ 'ok' : Course, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'finalizeCoursePurchase' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'getCallerUserProfile' : IDL.Func([], [Result_1], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [Result_3], ['query']),
  'getCourses' : IDL.Func([], [Result_2], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSystemHealth' : IDL.Func([], [SystemHealth], ['query']),
  'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [Result_1], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCoursePrice' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CodingChallengeResult = IDL.Record({
    'title' : IDL.Text,
    'testCasesPassed' : IDL.Nat,
    'score' : IDL.Nat,
    'challengeId' : IDL.Text,
    'totalTestCases' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'title' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'quizId' : IDL.Text,
  });
  const CourseId = IDL.Text;
  const Certificate = IDL.Record({
    'id' : IDL.Text,
    'userName' : IDL.Text,
    'completionDate' : IDL.Int,
    'userId' : IDL.Principal,
    'codingChallengeResults' : IDL.Vec(CodingChallengeResult),
    'quizResults' : IDL.Vec(QuizResult),
    'courseTitle' : IDL.Text,
    'engagementScore' : IDL.Nat,
    'courseId' : CourseId,
  });
  const AssessmentResultType = IDL.Variant({
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'success' : IDL.Bool,
  });
  const AssessmentType = IDL.Variant({
    'quiz' : IDL.Null,
    'codingChallenge' : IDL.Null,
  });
  const Time = IDL.Int;
  const AssessmentResult = IDL.Record({
    'result' : AssessmentResultType,
    'assessmentType' : AssessmentType,
    'timestamp' : Time,
    'assessmentId' : IDL.Text,
  });
  const LessonId = IDL.Text;
  const VideoEngagement = IDL.Record({
    'participationScore' : IDL.Nat,
    'lessonId' : LessonId,
    'attentionScore' : IDL.Nat,
  });
  const CodingChallengeAttempt = IDL.Record({
    'avgScore' : IDL.Nat,
    'attempts' : IDL.Nat,
    'challengeId' : IDL.Text,
  });
  const QuizTry = IDL.Record({
    'avgScore' : IDL.Nat,
    'attempts' : IDL.Nat,
    'quizId' : IDL.Text,
  });
  const EngagementMetrics = IDL.Record({
    'videoEngagement' : IDL.Vec(VideoEngagement),
    'codingChallengeAttempts' : IDL.Vec(CodingChallengeAttempt),
    'attentionScore' : IDL.Nat,
    'quizTries' : IDL.Vec(QuizTry),
  });
  const CourseProgress = IDL.Record({
    'totalLessons' : IDL.Nat,
    'progress' : IDL.Nat,
    'completedLessons' : IDL.Nat,
    'courseId' : CourseId,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'isInstructor' : IDL.Bool,
    'earnedCertificates' : IDL.Vec(Certificate),
    'assessmentHistory' : IDL.Vec(AssessmentResult),
    'engagementMetrics' : EngagementMetrics,
    'name' : IDL.Text,
    'purchasedCourses' : IDL.Vec(CourseId),
    'courseProgress' : IDL.Vec(CourseProgress),
  });
  const Result_1 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const CodingChallenge = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
    'videoBlob' : IDL.Record({ 'id' : IDL.Text, 'url' : IDL.Text }),
  });
  const Quiz = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'questions' : IDL.Vec(IDL.Text),
  });
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'codingChallenges' : IDL.Vec(CodingChallenge),
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
    'price' : IDL.Nat,
    'quizzes' : IDL.Vec(Quiz),
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Opt(Course), 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Vec(Course), 'err' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SystemHealth = IDL.Record({
    'courseCount' : IDL.Nat,
    'initializationComplete' : IDL.Bool,
    'adminAssigned' : IDL.Bool,
    'coursesLoaded' : IDL.Bool,
    'systemReady' : IDL.Bool,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const Result = IDL.Variant({ 'ok' : Course, 'err' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'finalizeCoursePurchase' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'getCallerUserProfile' : IDL.Func([], [Result_1], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'getCourses' : IDL.Func([], [Result_2], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSystemHealth' : IDL.Func([], [SystemHealth], ['query']),
    'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [Result_1], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCoursePrice' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };